type Block @entity {
	id:                           ID!
	number:                       BigInt!
	timestamp:                    BigInt!
	transactions:                 [Transaction!]! @derivedFrom(field: "block")
}
