type Transaction @entity {
	id:                           ID!
	block:                        Block!
	timestamp:                    BigInt!
	index:                        BigInt!
	from:                         Address!
	events:                       [Event!]! @derivedFrom(field: "transaction")
}
